title: HYOJAE

url: https://github.com/hyojaekim
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: hyojaekim
  email: hyojaedev@gmail.com

google_analytics: "UA-58263416-1"