# Site settings
title: Kim Hyojae
description: Kim Hyojae
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyojaekim.github.io" # the base hostname & protocol for your site

# User settings
username: HYOJAE
user_description: Kim Hyojae
user_title: Backend Developer
email: hyojaedev@gmail.com
github_username:  hyojaekim
twitter_username:
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
