title: HYOJAE
description: Develop Study Blog

url: https://github.com/hyojaekim
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
# plugins: [jekyll-paginate]
plugins:
 - jekyll-paginate
 - jekyll-archives
 - jekyll-time-to-read
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: Articles
    url: /articles

social:
  github: hyojaekim
  email: hyojaedev@gmail.com

google_analytics: "UA-152958706-1"
